//
//  CUIOpenFileDialog.h
//  MacOSX
//
//  Created by Julien Moreau-Mathis on 12/11/12.
//
//

#ifndef __C_PARTICLE_SYSTEMS_TYPES_H_INCLUDED__
#define __C_PARTICLE_SYSTEMS_TYPES_H_INCLUDED__

#include "../../../SPARK/SPARK155/include/SPK.h"
#include "../../../SPARK/SPARK155/include/SPK_IRR.h"

enum E_PS_DATA_TYPE {
    EPSDT_SYSTEM = 0,
    EPSDT_GROUP,
    EPSDT_EMITTER,
    EPSDT_RENDERER,
    EPSDT_MODEL,
	EPSDT_MODIFIER
};

enum E_PS_ZONE_TYPE {
	EZT_AABOX = 0,
	EZT_CYLINDER,
	EZT_LINE,
	EZT_PLANE,
	EZT_POINT,
	EZT_RING,
	EZT_SPHERE,
	EZT_UNKNOWN
};

enum E_PS_EMITTER_TYPE {
	ECET_STRAIGHT = 0,
	ECET_STATIC,
	ECET_SPHERIC,
	ECET_RANDOM,
	ECET_NORMAL
};

enum E_PS_GROUP_MODIFIER_TYPE {
	EGMT_COLLISION = 0,
	EGMT_DESTROYER,
	EGMT_LINEAR_FORCE,
	//EGMT_MODIFIER_GROUP,
	EGMT_OBSTACLE,
	EGMT_POINT_MASS,
	EGMT_ROTATOR,
	EGMT_VORTEX
};

enum E_PS_PARAM_TYPE {
	EPSPT_RAND=0,
	EPSPT_BIRTH_DEATH
};

#endif
